// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
export default defineConfig({
  site: 'https://www.ambitsol.co',
  integrations: [sitemap()],
  redirects: {
    // Core pages
    '/about-us': 'https://www.ambitsol.co/about',
    '/what-we-do': 'https://www.ambitsol.co/about',
    '/who-we-are': 'https://www.ambitsol.co/about',
    '/contact-us.php': 'https://www.ambitsol.co/contact',
    '/how-we-work': 'https://www.ambitsol.co/how-it-works',
    '/faq': 'https://www.ambitsol.co',
    '/price': 'https://www.ambitsol.co/',
    '/plan-price.php': 'https://www.ambitsol.co/',
    '/thank-you': 'https://www.ambitsol.co/',
    '/review.php': 'https://www.ambitsol.co/',
    '/security': 'https://www.ambitsol.co/',
    '/privacy-policy': 'https://www.ambitsol.co/privacy',
    '/privacy-policy.php': 'https://www.ambitsol.co/privacy',
    '/terms-conditions': 'https://www.ambitsol.co/terms',

    // Blog indexes
    '/blogs': 'https://www.ambitsol.co/blog',
    '/articles': 'https://www.ambitsol.co/blog',

    // Article redirects — distributed across 3 blog posts
    '/article/bookkeeping-for-painters-keeping-your-business-finances-on-canvas': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/the-ultimate-guide-to-interior-design-bookkeeping': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/20-bookkeeping-tips-for-interior-designers': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/account-payables-in-supply-chain-management-ensuring-smooth-operation': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/understanding-the-role-of-accounts-payable-in-financial-statements': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/account-payable-a-comprehensive-guide-for-beginners': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/role-of-account-payables-in-cost-control-and-budgeting': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/account-payables-training-empowering-your-team-for-success': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/optimizing-discounts-and-early-payment-terms-in-account-payable': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/the-importance-of-internal-controls-in-account-payables-management': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/account-payables-outsourcing-vs-in-house-making-the-right-decision': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/managing-account-payables-in-a-remote-work-environment': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/a-step-by-step-guide-how-to-do-restaurant-accounting': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/accounts-payable-aging-strategies-for-efficient-financial-management': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/effective-strategies-for-mitigating-financial-risks-in-accounts-payable': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/everything-you-need-to-know-about-federal-taxes': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/how-outsource-accounting-can-help-your-real-estate-business-thrive': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/mastering-account-payables-tracking-and-reporting-for-financial-analysis': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/maximizing-business-success-through-strong-vendor-relationships-in-accounts-payable': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/the-role-of-technology-in-modern-account-payables-management': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/2023-ecommerce-accounting-simplify-your-books-and-boost-your-business': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/5-common-mistakes-cpas-make-while-outsourcing-and-how-to-avoid-them': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/account-payable-fraud-prevention-safeguarding-your-business': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/account-payables-automation-boosting-efficiency-and-accuracy': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/account-payables-best-practices-for-timely-payments': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/account-payables-process-improvement-identifying-bottlenecks-and-enhancements': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/account-payables-vs-account-receivables-understanding-the-key-difference': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/accounts-payable-metrics-kpi-for-tracking-efficiency': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/avoiding-accounts-payable-pitfalls-essential-tips-for-financial-success': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/data-security-in-e-commerce-bookkeeping-protecting-your-financial-information': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/discover-the-secret-to-effortless-financial-success-professional-bookkeeping-service-revealed': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/e-commerce-bookkeeping-a-comprehensive-guide': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/ecommerce-accounting-101-key-principles-for-online-business-owners': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/effective-payroll-management-for-restaurants-ensuring-financial-success': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/effective-vendor-management-in-accounts-payable-for-ultimate-success': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/how-can-offshore-staffing-help-you-scale-your-tax-and-accounting-firm-without-sacrificing-quality': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/how-to-choose-the-right-online-bookkeeping-service-for-your-business': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/how-to-conduct-financial-analysis-for-your-restaurant': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/how-to-figure-out-sales-tax-like-a-pro': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/how-to-outsource-bookkeeping-a-comprehensive-guide': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/impact-of-late-payments-on-small-businesses-strategies-for-accounts-receivable-management': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/making-sure-everything-is-accurate-with-accounts-payable-audit': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/mastering-accounts-payable-forecasting-for-business-success': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/mastering-accounts-payable-reconciliation-for-financial-accuracy': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/mastering-ecommerce-sales-tax-book-keeping-perspective': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/mastering-restaurant-expense-management-top-strategies-for-us-accountants-and-cpas': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/maximizing-value-3-ways-for-finance-accounting-outsourcing': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/myths-with-offshore-outsourcing': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/outsourcing-services-or-dedicated-offshore-staffing-understanding-the-differences': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/pros-and-cons-of-outsourcing-your-accounts-payable': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/sales-tax-in-the-usa': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/selecting-an-accounting-outsourcing-partner-for-your-business': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/strategic-tax-planning-for-restaurants-maximizing-savings': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/the-benefits-of-electronic-invoicing-in-accounts-payable': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/the-importance-of-us-accounting-standards-for-businesses': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/top-10-ap-automation-trends-2024-future-of-account-payables': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/top-5-common-tax-filing-errors-and-how-to-avoid-them': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/understanding-debits-and-credits-a-comprehensive-guide': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/article/understanding-the-value-of-account-payables-management-for-business-success': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/article/vendor-negotiation-strategies-for-optimizing-account-payables': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/article/ambit-tax-accounting-bookkeeping-services': 'https://www.ambitsol.co/services/finance-accounting-tax/us/overview',
    '/how-cfos-can-drive-maximum-value-in-business-with-outsourcing': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/interior-designer-bookkeeping-service.php': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',
    '/lacerte-bookkeeping-service.php': 'https://www.ambitsol.co/blog/restaurant-tax-planning',
    '/selecting-an-accounting-outsourcing-partner-for-your-business': 'https://www.ambitsol.co/blog/ap-outsourcing-vs-inhouse',
    '/when-is-it-appropriate-to-outsource-your-accounting-and-bookkeeping': 'https://www.ambitsol.co/blog/ecommerce-accounting-101',

    // Service pages
    '/services': 'https://www.ambitsol.co/services/finance-accounting-tax/us/overview',
    '/services/accounting-bookkeeping': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/bookkeeping-and-accounting': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/catch-up-bookkeeping': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/construction-accounting': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/invoice-processing': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/retail-accounting': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/tax-services': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/virtual-assistance': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/accounts-bookkeeping': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/ertc': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/service/accounts-payable-management': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/service/finance-controller-services': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/service/tax-return-preparation-services': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/services/accounts-payable': 'https://www.ambitsol.co/services/bpo',
    '/services/accounts-receivable': 'https://www.ambitsol.co/services/bpo',
    '/services/dedicated-staffing': 'https://www.ambitsol.co/services/finance-accounting-tax/us/payroll',
    '/services/payroll': 'https://www.ambitsol.co/services/finance-accounting-tax/us/payroll',
    '/services/tax-return': 'https://www.ambitsol.co/services/finance-accounting-tax/us/tax-compliance',
    '/services/tax-service': 'https://www.ambitsol.co/services/finance-accounting-tax/us/tax-compliance',
    '/services/financial-reporting': 'https://www.ambitsol.co/services/finance-accounting-tax/us/financial-management',
    '/remote-accounting-tax-solutions': 'https://www.ambitsol.co/services/finance-accounting-tax/us/tax-compliance',

    // Legacy .php and slug pages
    '/accounts-receivable-service.php': 'https://www.ambitsol.co/services/bpo',
    '/bakery-stores-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/bookkeeping-accounting-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/chiropracters-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/common-myths-with-offshore-outsourcing': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/construction-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/consumer-goods-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/dental-practice-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/quickbooks-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/shopify-store-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/accounting-bookkeeping',
    '/liquor-store-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/overview',
    '/monthly-financial-reporting.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/overview',
    '/payroll-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/payroll',
    '/tax-return-preparation-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/tax-compliance',
    '/transition-accounting-to-outsourcing-model-with-ease': 'https://www.ambitsol.co/services/finance-accounting-tax/us/tax-compliance',
    '/veterinary-bookkeeping-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/tax-compliance',
    '/virtual-assistance-service.php': 'https://www.ambitsol.co/services/finance-accounting-tax/us/tax-compliance',
  },
  vite: {
    plugins: [tailwindcss()]
  }
});
